AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: NM2TECH Analytics Shorts Backend API

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: nodejs18.x
    Environment:
      Variables:
        NODE_ENV: production

Resources:
  AnalyticsAPI:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.handler
      CodeUri: backend/
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
        RootEvent:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'
      Environment:
        Variables:
          OPENAI_API_KEY: !Ref OpenAIApiKey

  AnalyticsHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
          - PATCH
        AllowHeaders:
          - '*'
        MaxAge: 300

Parameters:
  OpenAIApiKey:
    Type: String
    Default: ''
    Description: OpenAI API Key (optional, for AI insights)
    NoEcho: true

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${AnalyticsHttpApi}.execute-api.${AWS::Region}.amazonaws.com'
    Export:
      Name: AnalyticsApiUrl





